export const dataThemeProfile = [
    {
        id:'dark',
        name:'Dark',
        color:'#000000',
        colorText:'#ffffff'
    },
    {
        id:'light',
        name:'Light',
        color:'#ffffff',
        colorText:'#000000'
    },
    {
        id:'blue',
        name:'Blue',
        color:'#0000ff',
        colorText:'#ffffff'
    },
    {
        id:'green',
        name:'Green',
        color:'#00ff00',
        colorText:'#ffffff'
    },
    {
        id:'red',
        name:'Red',
        color:'#ff0000',
        colorText:'#ffffff'
    }
]